WeaponShop/config/routes.rb
WeaponShop::Application.routes.draw do

  resources :raitings

  resources :viewscounts

  get 'admin' => 'admin#index'
  controller :sessions do 
    get 'login' => :new 
    post 'login' => :create 
    delete 'logout' => :destroy 
  end

  post '/setraiting/' => "raitings#update"
  
  resources :product_reitings

  resources :users

  resources :line_items

  resources :carts

  get "static_pages/bow"
  get "static_pages/crossbow"
  get "static_pages/cart"
  get "static_pages/registration"
  get "static_pages/signin"
  get "static_pages/getxml"
  get "static_pages/crossbows"
  get "static_pages/bows"
  get "static_pages/home"
  resources :bowtypes

  resources :bows

  resources :crossbowtypes

  resources :crossbows

end

WeaponShop/app/models/bow.rb
class Bow < ActiveRecord::Base
	belongs_to :bowtype
	
	has_attached_file :mainphoto

	has_many :line_items

	before_destroy :ensure_not_referenced_by_any_line_item

	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors.add(:base, 'Line items present')
			return false
		end
	end
end

WeaponShop/app/models/bowtype.rb
class Bowtype < ActiveRecord::Base
	has_many :bow
end

WeaponShop/app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
end

WeaponShop/app/models/crossbow.rb
class Crossbow < ActiveRecord::Base
	belongs_to :crossbowtype

	has_attached_file :mainphoto, :default_url => "/assets/crossbow_view.jpg"
	attr_accessor :mainphoto_file_name
  	attr_accessor :mainphoto_content_type
  	attr_accessor :mainphoto_file_size

  	validates_attachment_content_type :mainphoto, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	has_many :line_items

	before_destroy :ensure_not_referenced_by_any_line_item

	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors.add(:base, 'Line items present')
			return false
		end
	end

	def self.get_crossbows_with_type(idtype)
		return Crossbow.where("crossbowtype_id = " + idtype.to_s)
	end
end

WeaponShop/app/models/crossbowtype.rb
class Crossbowtype < ActiveRecord::Base
	has_many :crossbow
end

WeaponShop/app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :bow
	belongs_to :crossbow
	belongs_to :cart
end

WeaponShop/app/models/product_reiting.rb
class ProductReiting < ActiveRecord::Base
end

WeaponShop/app/models/raiting.rb
class Raiting < ActiveRecord::Base
end

WeaponShop/app/models/user.rb
class User < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true
	validates :password, :confirmation => true 
	attr_accessor :password_confirmation 
	attr_reader :password

	validate :password_must_be_present


	def User.authenticate(name, password) 
		if user = find_by_name(name) 
			if user.hashed_password == encrypt_password(password, user.salt)
				user 
			end 
		end 
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	def password=(password)
		@password = password

		if password.present? 
			generate_salt 
			self.hashed_password = self.class.encrypt_password(password, salt)
		end
	end

	

	private

	def password_must_be_present 
		errors.add(:password, "Missing password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s 
	end


end

WeaponShop/app/models/viewscount.rb
class Viewscount < ActiveRecord::Base
end

WeaponShop/app/controllers/crossbowtypes_controller.rb
class CrossbowtypesController < ApplicationController
  before_action :set_crossbowtype, only: [:show, :edit, :update, :destroy]

  # GET /crossbowtypes
  # GET /crossbowtypes.json
  def index
    @crossbowtypes = Crossbowtype.all
  end

  # GET /crossbowtypes/1
  # GET /crossbowtypes/1.json
  def show
  end

  # GET /crossbowtypes/new
  def new
    @crossbowtype = Crossbowtype.new
  end

  # GET /crossbowtypes/1/edit
  def edit
  end

  # POST /crossbowtypes
  # POST /crossbowtypes.json
  def create
    @crossbowtype = Crossbowtype.new(crossbowtype_params)

    respond_to do |format|
      if @crossbowtype.save
        format.html { redirect_to @crossbowtype, notice: 'Crossbowtype was successfully created.' }
        format.json { render action: 'show', status: :created, location: @crossbowtype }
      else
        format.html { render action: 'new' }
        format.json { render json: @crossbowtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crossbowtypes/1
  # PATCH/PUT /crossbowtypes/1.json
  def update
    respond_to do |format|
      if @crossbowtype.update(crossbowtype_params)
        format.html { redirect_to @crossbowtype, notice: 'Crossbowtype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @crossbowtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crossbowtypes/1
  # DELETE /crossbowtypes/1.json
  def destroy
    @crossbowtype.destroy
    respond_to do |format|
      format.html { redirect_to crossbowtypes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crossbowtype
      @crossbowtype = Crossbowtype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crossbowtype_params
      params.require(:crossbowtype).permit(:name)
    end
end

WeaponShop/app/helpers/admin_helper.rb
module AdminHelper
end

WeaponShop/app/helpers/application_helper.rb
module ApplicationHelper
end

WeaponShop/app/helpers/bows_helper.rb
module BowsHelper
end

WeaponShop/app/helpers/bowtypes_helper.rb
module BowtypesHelper
end

WeaponShop/app/helpers/carts_helper.rb
module CartsHelper
end

WeaponShop/app/helpers/crossbows_helper.rb
module CrossbowsHelper
end

WeaponShop/app/helpers/crossbowtypes_helper.rb
module CrossbowtypesHelper
end

WeaponShop/app/helpers/line_items_helper.rb
module LineItemsHelper
end

WeaponShop/app/helpers/raitings_helper.rb
module RaitingsHelper
end

WeaponShop/app/helpers/sessions_helper.rb
module SessionsHelper
end

WeaponShop/app/helpers/users_helper.rb
module UsersHelper
end

WeaponShop/app/views/crossbowtypes/_form.html.erb
<%= form_for(@crossbowtype) do |f| %>
  <% if @crossbowtype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crossbowtype.errors.count, "error") %> prohibited this crossbowtype from being saved:</h2>

      <ul>
      <% @crossbowtype.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WeaponShop/app/views/crossbowtypes/edit.html.erb
<h1>Editing crossbowtype</h1>

<%= render 'form' %>

<%= link_to 'Show', @crossbowtype %> |
<%= link_to 'Back', crossbowtypes_path %>

WeaponShop/app/views/crossbowtypes/index.html.erb
<h1>Listing crossbowtypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @crossbowtypes.each do |crossbowtype| %>
      <tr>
        <td><%= crossbowtype.name %></td>
        <td><%= link_to 'Show', crossbowtype %></td>
        <td><%= link_to 'Edit', edit_crossbowtype_path(crossbowtype) %></td>
        <td><%= link_to 'Destroy', crossbowtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crossbowtype', new_crossbowtype_path %>

WeaponShop/app/views/crossbowtypes/new.html.erb
<h1>New crossbowtype</h1>

<%= render 'form' %>

<%= link_to 'Back', crossbowtypes_path %>

WeaponShop/app/views/crossbowtypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crossbowtype.name %>
</p>

<%= link_to 'Edit', edit_crossbowtype_path(@crossbowtype) %> |
<%= link_to 'Back', crossbowtypes_path %>