WeaponShop/config/routes.rb
WeaponShop::Application.routes.draw do

  resources :raitings

  resources :viewscounts

  get 'admin' => 'admin#index'
  controller :sessions do 
    get 'login' => :new 
    post 'login' => :create 
    delete 'logout' => :destroy 
  end

  post '/setraiting/' => "raitings#update"
  
  resources :product_reitings

  resources :users

  resources :line_items

  resources :carts

  get "static_pages/bow"
  get "static_pages/crossbow"
  get "static_pages/cart"
  get "static_pages/registration"
  get "static_pages/signin"
  get "static_pages/getxml"
  get "static_pages/crossbows"
  get "static_pages/bows"
  get "static_pages/home"
  resources :bowtypes

  resources :bows

  resources :crossbowtypes

  resources :crossbows

end

WeaponShop/app/models/bow.rb
class Bow < ActiveRecord::Base
	belongs_to :bowtype
	
	has_attached_file :mainphoto

	has_many :line_items

	before_destroy :ensure_not_referenced_by_any_line_item

	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors.add(:base, 'Line items present')
			return false
		end
	end
end

WeaponShop/app/models/bowtype.rb
class Bowtype < ActiveRecord::Base
	has_many :bow
end

WeaponShop/app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
end

WeaponShop/app/models/crossbow.rb
class Crossbow < ActiveRecord::Base
	belongs_to :crossbowtype

	has_attached_file :mainphoto, :default_url => "/assets/crossbow_view.jpg"
	attr_accessor :mainphoto_file_name
  	attr_accessor :mainphoto_content_type
  	attr_accessor :mainphoto_file_size

  	validates_attachment_content_type :mainphoto, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	has_many :line_items

	before_destroy :ensure_not_referenced_by_any_line_item

	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors.add(:base, 'Line items present')
			return false
		end
	end

	def self.get_crossbows_with_type(idtype)
		return Crossbow.where("crossbowtype_id = " + idtype.to_s)
	end
end

WeaponShop/app/models/crossbowtype.rb
class Crossbowtype < ActiveRecord::Base
	has_many :crossbow
end

WeaponShop/app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :bow
	belongs_to :crossbow
	belongs_to :cart
end

WeaponShop/app/models/product_reiting.rb
class ProductReiting < ActiveRecord::Base
end

WeaponShop/app/models/raiting.rb
class Raiting < ActiveRecord::Base
end

WeaponShop/app/models/user.rb
class User < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true
	validates :password, :confirmation => true 
	attr_accessor :password_confirmation 
	attr_reader :password

	validate :password_must_be_present


	def User.authenticate(name, password) 
		if user = find_by_name(name) 
			if user.hashed_password == encrypt_password(password, user.salt)
				user 
			end 
		end 
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	def password=(password)
		@password = password

		if password.present? 
			generate_salt 
			self.hashed_password = self.class.encrypt_password(password, salt)
		end
	end

	

	private

	def password_must_be_present 
		errors.add(:password, "Missing password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s 
	end


end

WeaponShop/app/models/viewscount.rb
class Viewscount < ActiveRecord::Base
end

WeaponShop/app/controllers/bowtypes_controller.rb
class BowtypesController < ApplicationController
  before_action :set_bowtype, only: [:show, :edit, :update, :destroy]

  # GET /bowtypes
  # GET /bowtypes.json
  def index
    @bowtypes = Bowtype.all
  end

  # GET /bowtypes/1
  # GET /bowtypes/1.json
  def show
  end

  # GET /bowtypes/new
  def new
    @bowtype = Bowtype.new
  end

  # GET /bowtypes/1/edit
  def edit
  end

  # POST /bowtypes
  # POST /bowtypes.json
  def create
    @bowtype = Bowtype.new(bowtype_params)

    respond_to do |format|
      if @bowtype.save
        format.html { redirect_to @bowtype, notice: 'Bowtype was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bowtype }
      else
        format.html { render action: 'new' }
        format.json { render json: @bowtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bowtypes/1
  # PATCH/PUT /bowtypes/1.json
  def update
    respond_to do |format|
      if @bowtype.update(bowtype_params)
        format.html { redirect_to @bowtype, notice: 'Bowtype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bowtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bowtypes/1
  # DELETE /bowtypes/1.json
  def destroy
    @bowtype.destroy
    respond_to do |format|
      format.html { redirect_to bowtypes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bowtype
      @bowtype = Bowtype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bowtype_params
      params.require(:bowtype).permit(:name)
    end
end

WeaponShop/app/helpers/admin_helper.rb
module AdminHelper
end

WeaponShop/app/helpers/application_helper.rb
module ApplicationHelper
end

WeaponShop/app/helpers/bows_helper.rb
module BowsHelper
end

WeaponShop/app/helpers/bowtypes_helper.rb
module BowtypesHelper
end

WeaponShop/app/helpers/carts_helper.rb
module CartsHelper
end

WeaponShop/app/helpers/crossbows_helper.rb
module CrossbowsHelper
end

WeaponShop/app/helpers/line_items_helper.rb
module LineItemsHelper
end

WeaponShop/app/helpers/raitings_helper.rb
module RaitingsHelper
end

WeaponShop/app/helpers/sessions_helper.rb
module SessionsHelper
end

WeaponShop/app/helpers/users_helper.rb
module UsersHelper
end

WeaponShop/app/helpers/viewscounts_helper.rb
module ViewscountsHelper
end

WeaponShop/app/views/bowtypes/_form.html.erb
<%= form_for(@bowtype) do |f| %>
  <% if @bowtype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bowtype.errors.count, "error") %> prohibited this bowtype from being saved:</h2>

      <ul>
      <% @bowtype.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WeaponShop/app/views/bowtypes/edit.html.erb
<h1>Editing bowtype</h1>

<%= render 'form' %>

<%= link_to 'Show', @bowtype %> |
<%= link_to 'Back', bowtypes_path %>

WeaponShop/app/views/bowtypes/index.html.erb
<h1>Listing bowtypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bowtypes.each do |bowtype| %>
      <tr>
        <td><%= bowtype.name %></td>
        <td><%= link_to 'Show', bowtype %></td>
        <td><%= link_to 'Edit', edit_bowtype_path(bowtype) %></td>
        <td><%= link_to 'Destroy', bowtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bowtype', new_bowtype_path %>

WeaponShop/app/views/bowtypes/new.html.erb
<h1>New bowtype</h1>

<%= render 'form' %>

<%= link_to 'Back', bowtypes_path %>

WeaponShop/app/views/bowtypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bowtype.name %>
</p>

<%= link_to 'Edit', edit_bowtype_path(@bowtype) %> |
<%= link_to 'Back', bowtypes_path %>